#!/bin/sh

rm -rf ./output
rm -rf ./output_test
rm -rf ./build

find Sogas -name "*.vcxproj*" -delete
find Sogas -name "*.sln" -delete
find Sogas -name "*.cmake" -delete
find Sogas -name "*CMakeCache.txt" -delete
find . -type d -name "CMakeFiles" -exec rm -rf {} + # Remove CMakeFiles directory
find . -type d -name "*.dir" -exec rm -rf {} + # Remove intermediate directory generated by VS2022
